# Form implementation generated from reading ui file 'Edit.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1097, 862)
        self.table = QtWidgets.QTableWidget(parent=Dialog)
        self.table.setEnabled(True)
        self.table.setGeometry(QtCore.QRect(0, 20, 1121, 741))
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(6, item)
        self.table.horizontalHeader().setDefaultSectionSize(150)
        self.edit = QtWidgets.QPushButton(parent=Dialog)
        self.edit.setGeometry(QtCore.QRect(870, 790, 131, 41))
        self.edit.setObjectName("edit")
        self.result = QtWidgets.QLineEdit(parent=Dialog)
        self.result.setGeometry(QtCore.QRect(140, 810, 541, 20))
        self.result.setObjectName("result")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "название сорта"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "степень обжарки"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "тип"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "описание вкуса"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "цена"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "объем упаковки(л)"))
        self.edit.setText(_translate("Dialog", "Изменить"))
